# https://github.com/DavidAnson/markdownlint

# MD033/no-inline-html - Inline HTML
MD033: false

# MD013/line-length - Line length
MD013: false

# MD025/single-title/single-h1: Multiple top-level headings in the same documentmarkdownlint
MD025: false
