repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: charts/_source/templates/
      - id: check-json
      - id: end-of-file-fixer
        exclude: layouts/shortcodes/current_version.html
      - id: check-symlinks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
    - id: markdownlint
