version: '3.1'
services:
  hugo:
      image: hugomods/hugo:${HUGO_VERSION-git-0.120.4}
      command: hugo server -D --bind 0.0.0.0 --poll 700ms
      volumes:
        - ".:/src"
      ports:
        - "1313:1313"
