{{- if eq .Values.format "PrometheusRuleCRD" }}
{{- $fullName := include "chart.fullname" . -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- if .Values.additionalPrometheusRuleLabels }}
{{ .Values.additionalPrometheusRuleLabels | toYaml | indent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ $.Values.rulesGroupName }}
      rules:
{{- range $name, $val := .Values.rules }}
{{- $_ := set . "name" $name }}
{{- $_ := set . "globalAdditionalExprLabels" $.Values.global.additionalExprLabels }}
{{- $_ := set . "globalAdditionalRuleLabels" $.Values.global.additionalRuleLabels }}
{{- $_ := set . "defaultRunbookUrl" $.Values.defaultRunbookUrl }}
{{- $_ := set . "chartVersion" $.Chart.Version }}

{{- include "chart.renderPrometheusRule" . | indent 8 -}}
{{- end }}
{{- end }}
