rule_files:
    - rules.yml

evaluation_interval: 1m

tests:

    - name: SQLExporterDown
      interval: 1m
      input_series:
          - series: 'up{service="sql-exporter", target="mydatabase"}'
            values: '0x10'
      alert_rule_test:
          - alertname: SQLExporterDown
            eval_time: 5m
            exp_alerts:
                - exp_labels:
                      service: sql-exporter
                      severity: critical
                  exp_annotations:
                      summary: "Exporter is down"
                      description: "SQL Exporter is down"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/postgresql/SQLExporterDown"
