rule_files:
    - rules.yml

evaluation_interval: 1m

tests:

    - name: PostgreSQLExporterScrapingLimit
      interval: 1m
      input_series:
          - series: 'pg_exporter_last_scrape_duration_seconds{instance="localhost:9187"}'
            values: 40x10
      alert_rule_test:
          - alertname: PostgreSQLExporterScrapingLimit
            eval_time: 5m
            exp_alerts:
                - exp_labels:
                      instance: localhost:9187
                      severity: warning
                  exp_annotations:
                      summary: "Exporter scraping take long time"
                      description: "localhost:9187 scraping take long time"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/postgresql/PostgreSQLExporterScrapingLimit"
