rule_files:
    - rules.yml

evaluation_interval: 1m

tests:

    - name: PostgreSQLInactivePhysicalReplicationSlot
      interval: 1m
      input_series:
          - series: 'pg_replication_slots_active{slot_type="physical", server="db1.unittest.eu-west-3.rds.amazonaws.com:5432", slot_name="unittest"}'
            values: 0x10
      alert_rule_test:
          - alertname: PostgreSQLInactivePhysicalReplicationSlot
            eval_time: 10m
            exp_alerts:
                - exp_labels:
                      server: db1.unittest.eu-west-3.rds.amazonaws.com:5432
                      slot_name: unittest
                      severity: warning
                  exp_annotations:
                      summary: "Physical replication slot is inactive"
                      description: "unittest on db1 is inactive"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/postgresql/PostgreSQLInactivePhysicalReplicationSlot"
