rule_files:
    - rules.yml

evaluation_interval: 1m

tests:

    - name: SQLExporterScrapingLimit
      interval: 1m
      input_series:
          - series: 'scrape_duration_seconds{job="sql-exporter", target=""}'
            values: 40x10
      alert_rule_test:
          - alertname: SQLExporterScrapingLimit
            eval_time: 5m
            exp_alerts:
                - exp_labels:
                      job: sql-exporter
                      severity: warning
                  exp_annotations:
                      summary: "Exporter scraping takes long time"
                      description: "SQL Exporter scraping is taking a long time"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/postgresql/SQLExporterScrapingLimit"
