rule_files:
    - rules.yml

evaluation_interval: 1m

tests:

    - name: RDSForcedMaintenance
      interval: 1m
      input_series:
          - series: 'rds_instance_info{aws_account_id="111111111111",aws_region="eu-west-3",dbidentifier="db1",pending_maintenance="forced"}'
            values: 1x60
          - series: 'rds_instance_info{aws_account_id="111111111111",aws_region="eu-west-3",dbidentifier="db2",pending_maintenance="auto-applied"}'
            values: 1x60
      alert_rule_test:
          - alertname: RDSForcedMaintenance
            eval_time: 1h
            exp_alerts:
                - exp_labels:
                      aws_account_id: 111111111111
                      aws_region: eu-west-3
                      dbidentifier: db1
                      severity: warning
                  exp_annotations:
                      description: "db1 has forced maintenance"
                      summary: "Instance has forced maintenance"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/rds/RDSForcedMaintenance"
                - exp_labels:
                      aws_account_id: 111111111111
                      aws_region: eu-west-3
                      dbidentifier: db2
                      severity: warning
                  exp_annotations:
                      description: "db2 has forced maintenance"
                      summary: "Instance has forced maintenance"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/rds/RDSForcedMaintenance"
