rule_files:
    - rules.yml

evaluation_interval: 1m

tests:

    - name: RDSNonCPUUtilization
      interval: 1m
      input_series:
          - series: 'rds_dbload_noncpu_average{aws_account_id="111111111111",aws_region="eu-west-3",dbidentifier="db1"}'
            values: 20x10  # 20 active queries
          - series: 'rds_instance_info{aws_account_id="111111111111",aws_region="eu-west-3",dbidentifier="db1",instance_class="t3.xlarge"}'
            values: 1x10
          - series: 'rds_instance_vcpu_average{aws_account_id="111111111111",aws_region="eu-west-3",dbidentifier="db1",instance_class="t3.xlarge"}'
            values: 4x10  # 4 vCPU
      alert_rule_test:
          - alertname: RDSNonCPUUtilization
            eval_time: 10m
            exp_alerts:
                - exp_labels:
                      aws_account_id: 111111111111
                      aws_region: eu-west-3
                      dbidentifier: db1
                      severity: warning
                  exp_annotations:
                      description: "db1 has 20 queries waiting for a reason other than the CPU"
                      summary: "db1 has high non CPU utilization"
                      runbook_url: "https://qonto.github.io/database-monitoring-framework/0.0.0/runbooks/rds/RDSNonCPUUtilization"
